-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.app_settings (
  key text NOT NULL,
  value boolean DEFAULT true,
  label text,
  CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);
CREATE TABLE public.asignaciones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  equipo text,
  cliente text,
  cedula text,
  onu text,
  plan text,
  tecnico_1 text,
  tecnico_2 text,
  fecha text,
  hora text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  user_id uuid,
  CONSTRAINT asignaciones_pkey PRIMARY KEY (id),
  CONSTRAINT asignaciones_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT asignaciones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.cierres (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid NOT NULL,
  fecha text,
  hora text,
  equipo text,
  precinto text,
  cliente text,
  cedula text,
  onu text,
  router text,
  mac_router text,
  zona text,
  power_go text,
  motivo_power_go text,
  estatus text,
  plan text,
  v_descarga text,
  v_subida text,
  puerto text,
  caja_nap text,
  potencia_nap text,
  potencia_cliente text,
  conectores text,
  metraje_usado text,
  metraje_desechado text,
  tensores text,
  patchcord text,
  rosetas text,
  tecnico_1 text,
  tecnico_2 text,
  observacion_final text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  codigo_carrete text,
  tecnico_id uuid,
  user_id uuid,
  CONSTRAINT cierres_pkey PRIMARY KEY (id),
  CONSTRAINT cierres_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT cierres_tecnico_id_fkey FOREIGN KEY (tecnico_id) REFERENCES auth.users(id),
  CONSTRAINT cierres_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.clientes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  nombre text NOT NULL,
  cedula text NOT NULL UNIQUE,
  direccion text NOT NULL,
  plan text NOT NULL,
  equipo text NOT NULL,
  onu text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  estatus text DEFAULT 'activo'::text,
  user_id uuid DEFAULT auth.uid(),
  CONSTRAINT clientes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.config_totales (
  id bigint NOT NULL,
  valle integer NOT NULL DEFAULT 0,
  propatria integer NOT NULL DEFAULT 0,
  la_vega integer NOT NULL DEFAULT 0,
  tejerias integer NOT NULL DEFAULT 0,
  coche integer NOT NULL DEFAULT 0,
  mes_acumulado integer NOT NULL DEFAULT 0,
  mes_actual text NOT NULL DEFAULT 'Febrero'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT config_totales_pkey PRIMARY KEY (id)
);
CREATE TABLE public.fallas (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehiculo_id uuid NOT NULL,
  reportado_por uuid,
  descripcion text NOT NULL,
  tipo_falla text NOT NULL,
  prioridad text NOT NULL DEFAULT 'Media'::text,
  estado text NOT NULL DEFAULT 'Pendiente'::text,
  fecha_solucion timestamp with time zone,
  notas_taller text,
  CONSTRAINT fallas_pkey PRIMARY KEY (id),
  CONSTRAINT fallas_vehiculo_id_fkey FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id),
  CONSTRAINT fallas_reportado_por_fkey FOREIGN KEY (reportado_por) REFERENCES auth.users(id)
);
CREATE TABLE public.fuel_daily_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  report_date date NOT NULL,
  generated_at timestamp with time zone NOT NULL DEFAULT now(),
  supervisor_id uuid,
  total_liters numeric NOT NULL,
  details jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT fuel_daily_reports_pkey PRIMARY KEY (id),
  CONSTRAINT fuel_daily_reports_supervisor_id_fkey FOREIGN KEY (supervisor_id) REFERENCES auth.users(id)
);
CREATE TABLE public.fuel_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  ticket_number text NOT NULL,
  fuel_date timestamp with time zone NOT NULL,
  vehicle_id uuid NOT NULL,
  driver_name text NOT NULL,
  liters numeric NOT NULL,
  mileage numeric NOT NULL,
  supervisor_id uuid NOT NULL,
  ticket_url text,
  notes text,
  CONSTRAINT fuel_logs_pkey PRIMARY KEY (id),
  CONSTRAINT fuel_logs_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehiculos(id),
  CONSTRAINT fuel_logs_supervisor_id_profiles_fkey FOREIGN KEY (supervisor_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.historial_reportes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  fecha timestamp with time zone NOT NULL DEFAULT now(),
  reporte text NOT NULL,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT historial_reportes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.installations (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  fecha date,
  mes text,
  tecnico_1 text,
  tecnico_2 text,
  router text,
  nombre_cliente text,
  cedula text,
  zona text,
  sector text,
  asesor text,
  estatus text,
  plan text,
  power_go text,
  servicio text,
  CONSTRAINT installations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_assignment_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assignment_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  serials jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT inventory_assignment_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_assignment_items_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.inventory_assignments(id),
  CONSTRAINT inventory_assignment_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_assignments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  code text NOT NULL UNIQUE,
  assigned_to uuid,
  status USER-DEFINED DEFAULT 'ACTIVE'::assignment_status,
  created_at timestamp with time zone DEFAULT now(),
  closed_at timestamp with time zone,
  received_by text,
  receiver_id text,
  team_id uuid,
  CONSTRAINT inventory_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_assignments_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id),
  CONSTRAINT inventory_assignments_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.inventory_audit_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  audit_id uuid NOT NULL,
  product_sku text NOT NULL,
  product_name text,
  theoretical_quantity numeric NOT NULL,
  physical_quantity numeric NOT NULL,
  difference numeric DEFAULT (physical_quantity - theoretical_quantity),
  unit_type text,
  notes text,
  reported_quantity integer DEFAULT 0,
  item_name text,
  item_sku text,
  product_id uuid,
  CONSTRAINT inventory_audit_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_audit_items_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES public.inventory_audits(id),
  CONSTRAINT inventory_audit_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_audits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  technician_id uuid,
  supervisor_id uuid DEFAULT auth.uid(),
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  team_id uuid,
  status text DEFAULT 'PENDING'::text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_audits_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_audits_technician_id_fkey FOREIGN KEY (technician_id) REFERENCES auth.users(id),
  CONSTRAINT inventory_audits_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.inventory_bundle_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  parent_product_id uuid NOT NULL,
  child_product_id uuid NOT NULL,
  quantity integer NOT NULL CHECK (quantity > 0),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_bundle_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_bundle_items_parent_product_id_fkey FOREIGN KEY (parent_product_id) REFERENCES public.inventory_products(id),
  CONSTRAINT inventory_bundle_items_child_product_id_fkey FOREIGN KEY (child_product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_combo_template_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_id uuid,
  product_id uuid,
  quantity integer NOT NULL DEFAULT 1,
  CONSTRAINT inventory_combo_template_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_combo_template_items_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.inventory_combo_templates(id),
  CONSTRAINT inventory_combo_template_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_combo_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT inventory_combo_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_products (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  sku text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  category text,
  current_stock integer DEFAULT 0,
  min_stock integer DEFAULT 5,
  location text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  is_bundle boolean DEFAULT false,
  requires_serial boolean DEFAULT false,
  damaged_stock integer DEFAULT 0,
  CONSTRAINT inventory_products_pkey PRIMARY KEY (id)
);
CREATE TABLE public.inventory_return_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  return_id uuid,
  product_id uuid,
  quantity integer NOT NULL,
  condition text DEFAULT 'GOOD'::text,
  serials jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT inventory_return_items_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_return_items_return_id_fkey FOREIGN KEY (return_id) REFERENCES public.inventory_returns(id),
  CONSTRAINT inventory_return_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_returns (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assignment_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  notes text,
  user_id uuid,
  CONSTRAINT inventory_returns_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_returns_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.inventory_assignments(id),
  CONSTRAINT inventory_returns_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.inventory_serials (
  serial_number text NOT NULL,
  product_id uuid NOT NULL,
  status USER-DEFINED DEFAULT 'AVAILABLE'::serial_status,
  location text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  initial_quantity integer DEFAULT 0,
  current_quantity integer DEFAULT 0,
  CONSTRAINT inventory_serials_pkey PRIMARY KEY (serial_number, product_id),
  CONSTRAINT inventory_serials_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id)
);
CREATE TABLE public.inventory_transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  product_id uuid,
  type USER-DEFINED NOT NULL,
  quantity integer NOT NULL,
  previous_stock integer NOT NULL,
  new_stock integer NOT NULL,
  reason text,
  user_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  assigned_to uuid,
  serials jsonb DEFAULT '[]'::jsonb,
  received_by text,
  receiver_id text,
  CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT inventory_transactions_product_id_fkey FOREIGN KEY (product_id) REFERENCES public.inventory_products(id),
  CONSTRAINT inventory_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT inventory_transactions_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES auth.users(id)
);
CREATE TABLE public.maintenance_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone DEFAULT now(),
  vehicle_id uuid NOT NULL,
  service_type text NOT NULL CHECK (service_type = ANY (ARRAY['OIL_CHANGE'::text, 'TIMING_BELT'::text, 'TIRE_ROTATION'::text, 'OTHER'::text, 'CHAIN_KIT'::text, 'WASH'::text, 'CORRECTIVE'::text])),
  mileage numeric NOT NULL,
  service_date date DEFAULT CURRENT_DATE,
  performed_by text,
  notes text,
  cost numeric DEFAULT 0,
  parts_used text,
  labor_cost numeric DEFAULT 0,
  parts_cost numeric DEFAULT 0,
  CONSTRAINT maintenance_logs_pkey PRIMARY KEY (id),
  CONSTRAINT maintenance_logs_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.network_nodes (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  nombre text NOT NULL,
  latitud double precision NOT NULL,
  longitud double precision NOT NULL,
  tipo text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT network_nodes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL,
  read boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  created_at timestamp with time zone DEFAULT now(),
  roles ARRAY NOT NULL DEFAULT '{invitado}'::text[],
  first_name text,
  last_name text,
  national_id text,
  department text,
  job_title text,
  team_id uuid,
  phone text,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT profiles_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id)
);
CREATE TABLE public.reportes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  vehiculo_id uuid NOT NULL,
  conductor text NOT NULL,
  departamento text NOT NULL,
  fecha_salida timestamp with time zone NOT NULL DEFAULT now(),
  km_salida numeric NOT NULL DEFAULT 0,
  gasolina_salida text NOT NULL,
  observaciones_salida text,
  aceite_salida boolean DEFAULT false,
  agua_salida boolean DEFAULT false,
  gato_salida boolean DEFAULT false,
  cruz_salida boolean DEFAULT false,
  triangulo_salida boolean DEFAULT false,
  caucho_salida boolean DEFAULT false,
  carpeta_salida boolean DEFAULT false,
  escalera_salida boolean DEFAULT false,
  onu_salida integer DEFAULT 0,
  ups_salida integer DEFAULT 0,
  fecha_entrada timestamp with time zone,
  km_entrada numeric,
  gasolina_entrada text,
  observaciones_entrada text,
  aceite_entrada boolean DEFAULT false,
  agua_entrada boolean DEFAULT false,
  gato_entrada boolean DEFAULT false,
  cruz_entrada boolean DEFAULT false,
  triangulo_entrada boolean DEFAULT false,
  caucho_entrada boolean DEFAULT false,
  carpeta_entrada boolean DEFAULT false,
  escalera_entrada boolean DEFAULT false,
  onu_entrada integer DEFAULT 0,
  ups_entrada integer DEFAULT 0,
  casco_salida boolean DEFAULT false,
  luces_salida boolean DEFAULT false,
  herramientas_salida boolean DEFAULT false,
  casco_entrada boolean DEFAULT false,
  luces_entrada boolean DEFAULT false,
  herramientas_entrada boolean DEFAULT false,
  user_id uuid,
  CONSTRAINT reportes_pkey PRIMARY KEY (id),
  CONSTRAINT reportes_vehiculo_id_fkey FOREIGN KEY (vehiculo_id) REFERENCES public.vehiculos(id),
  CONSTRAINT reportes_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.revisiones (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  cliente_id uuid NOT NULL,
  fecha text,
  hora text,
  equipo text,
  cliente text,
  cedula text,
  plan text,
  ubicacion text,
  precinto text,
  onu text,
  mac_onu text,
  caja_nap text,
  cant_puertos text,
  puerto_conectado text,
  coordenadas text,
  potencia_nap text,
  potencia_cliente text,
  observacion text,
  user_id uuid,
  CONSTRAINT revisiones_pkey PRIMARY KEY (id),
  CONSTRAINT revisiones_cliente_id_fkey FOREIGN KEY (cliente_id) REFERENCES public.clientes(id),
  CONSTRAINT revisiones_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.soportes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cliente_id uuid,
  tecnico_id uuid,
  fecha text,
  hora text,
  precinto text,
  caja_nap text,
  potencia text,
  coordenadas text,
  cantidad_puertos text,
  puerto text,
  zona text,
  estatus text DEFAULT 'Realizado'::text,
  causa text,
  codigo_carrete text,
  metraje_usado numeric DEFAULT 0,
  metraje_desechado numeric DEFAULT 0,
  conectores integer DEFAULT 0,
  tensores integer DEFAULT 0,
  patchcord integer DEFAULT 0,
  rosetas integer DEFAULT 0,
  onu_anterior text,
  onu_nueva text,
  observacion text,
  realizado_por text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cedula text,
  potencia_nap text,
  potencia_cliente text,
  has_evidence boolean DEFAULT false,
  download_speed numeric,
  upload_speed numeric,
  ping_latency numeric,
  CONSTRAINT soportes_pkey PRIMARY KEY (id)
);
CREATE TABLE public.system_settings (
  key text NOT NULL,
  value jsonb NOT NULL,
  description text,
  updated_at timestamp with time zone DEFAULT now(),
  updated_by uuid,
  CONSTRAINT system_settings_pkey PRIMARY KEY (key),
  CONSTRAINT system_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES auth.users(id)
);
CREATE TABLE public.teams (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  name text NOT NULL UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT teams_pkey PRIMARY KEY (id)
);
CREATE TABLE public.technician_daily_reports (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  team_id uuid,
  date text NOT NULL,
  vehicle_id uuid,
  onu_serials jsonb DEFAULT '[]'::jsonb,
  router_serials jsonb DEFAULT '[]'::jsonb,
  materials jsonb DEFAULT '{}'::jsonb,
  spools jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  conectores_used integer DEFAULT 0,
  conectores_remaining integer DEFAULT 0,
  conectores_defective integer DEFAULT 0,
  tensores_used integer DEFAULT 0,
  tensores_remaining integer DEFAULT 0,
  patchcords_used integer DEFAULT 0,
  patchcords_remaining integer DEFAULT 0,
  rosetas_used integer DEFAULT 0,
  clients_snapshot jsonb DEFAULT '[]'::jsonb,
  CONSTRAINT technician_daily_reports_pkey PRIMARY KEY (id),
  CONSTRAINT technician_daily_reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT technician_daily_reports_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id),
  CONSTRAINT technician_daily_reports_vehicle_id_fkey FOREIGN KEY (vehicle_id) REFERENCES public.vehiculos(id)
);
CREATE TABLE public.user_devices (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  fcm_token text NOT NULL UNIQUE,
  device_name text,
  platform text,
  last_active timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_devices_pkey PRIMARY KEY (id),
  CONSTRAINT user_devices_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.vehiculos (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  codigo text NOT NULL UNIQUE,
  placa text NOT NULL,
  modelo text NOT NULL,
  año text,
  capacidad_tanque text,
  color text,
  tipo_combustible text,
  foto_url text,
  tipo text,
  current_fuel_level integer DEFAULT 100,
  last_fuel_update timestamp with time zone DEFAULT now(),
  last_oil_change_km numeric,
  last_timing_belt_km numeric,
  last_chain_kit_km numeric,
  last_wash_date timestamp with time zone,
  assigned_driver_id uuid,
  department text,
  odometro_averiado boolean DEFAULT false,
  kilometraje numeric DEFAULT 0,
  CONSTRAINT vehiculos_pkey PRIMARY KEY (id),
  CONSTRAINT vehiculos_assigned_driver_id_fkey FOREIGN KEY (assigned_driver_id) REFERENCES public.profiles(id)
);