-- SEED desde ESTUDIO DE MERCADO.xlsx - 4 zonas
-- Zonas: Altos Mirandinos, Propatria, El Valle, Tejerías

-- ============ ALTOS MIRANDINOS ============
INSERT INTO ofertas_competencia (operador_id, estado, municipio, parroquia, tipo_novedad, velocidad_mb, precio_mensual, es_promocion, nombre_plan, tecnologia, costo_instalacion, servicios_adicionales, fuente, fecha_reporte, asesor_nombre) VALUES
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 300, 33, false, 'Plan 1', 'FTTH', 40, '[{"nombre":"TV 150 canales","precio":"0","condicion":"Incluido"},{"nombre":"ONU Router","precio":"40","condicion":"Compra"},{"nombre":"ONU Basica","precio":"30","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 600, 40, false, 'Plan 2', 'FTTH', 40, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 1000, 60, false, 'Plan 3', 'FTTH', 40, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 100, 35, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV","precio":"0","condicion":"Incluido"},{"nombre":"ONT","precio":"25","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 200, 42, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 600, 60, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 1000, 80, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 300, 30, false, 'Plan 1', 'FTTH', 39, '[{"nombre":"ONU Router","precio":"39","condicion":"Compra"},{"nombre":"ONU Basica","precio":"29","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 600, 35, false, 'Plan 2', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 900, 60, false, 'Plan 3', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Miranda', 'Guaicaipuro', 'Los Teques', 'Actualización General', 1500, 90, false, 'Plan 4', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado');

-- ============ PROPATRIA ============
INSERT INTO ofertas_competencia (operador_id, estado, municipio, parroquia, tipo_novedad, velocidad_mb, precio_mensual, es_promocion, nombre_plan, tecnologia, costo_instalacion, servicios_adicionales, fuente, fecha_reporte, asesor_nombre) VALUES
((SELECT id FROM operadores_competencia WHERE nombre='Tu Red 18'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 150, 30, false, 'Plan 1', 'FTTH', 65, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tu Red 18'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 250, 35, false, 'Plan 2', 'FTTH', 100, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tu Red 18'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 350, 45, false, 'Plan 3', 'FTTH', 110, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SolucionTV 555'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 200, 21, false, 'Plan 1', 'FTTH', 25, '[{"nombre":"TV","precio":"9","condicion":"Opcional"},{"nombre":"ONU Router","precio":"25","condicion":"Compra"},{"nombre":"ONU Basica","precio":"10","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SolucionTV 555'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 350, 26, false, 'Plan 2', 'FTTH', 25, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SolucionTV 555'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 30, false, 'Plan 3', 'FTTH', 25, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SolucionTV 555'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1500, 66, false, 'Plan 4', 'FTTH', 25, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 300, 33, false, 'Plan 1', 'FTTH', 40, '[{"nombre":"TV 150 canales","precio":"0","condicion":"Incluido"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 40, false, 'Plan 2', 'FTTH', 40, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Inter'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 60, false, 'Plan 3', 'FTTH', 40, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 300, 30, false, 'Plan 1', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 35, false, 'Plan 2', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 900, 60, false, 'Plan 3', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Fibex Telecom'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1500, 90, false, 'Plan 4', 'FTTH', 39, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WellComm'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 300, 20, false, 'Plan 1', 'Fibra', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WellComm'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 33, false, 'Plan 2', 'Fibra', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WellComm'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 900, 50, false, 'Plan 3', 'Fibra', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tech Pre'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 400, 25, false, 'Plan 1', 'FTTH', 85, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tech Pre'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 35, false, 'Plan 2', 'FTTH', 85, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tech Pre'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 800, 50, false, 'Plan 3', 'FTTH', 85, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Tech Pre'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 70, false, 'Plan 4', 'FTTH', 85, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='2 Net'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 400, 32, false, 'Plan 1', 'FTTH GPON', 24, '[{"nombre":"IPTV","precio":"0","condicion":"Incluido"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='2 Net'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 38, false, 'Plan 2', 'FTTH GPON', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='2 Net'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 800, 55, false, 'Plan 3', 'FTTH GPON', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WOW / MDS'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 450, 30, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV","precio":"8","condicion":"Opcional"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WOW / MDS'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 650, 38, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WOW / MDS'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 850, 56, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='WOW / MDS'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 95, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='G-Network'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 41, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV IPTV","precio":"0","condicion":"Incluido"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='G-Network'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 700, 52, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='G-Network'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 800, 58, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='G-Network'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 81, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='V-NET'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 400, 30, false, 'Plan 1', 'FTTH', 20, '[{"nombre":"TV","precio":"15","condicion":"Opcional"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='V-NET'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 35, false, 'Plan 2', 'FTTH', 20, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='V-NET'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 50, false, 'Plan 3', 'FTTH', 20, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Latin American Cable'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 200, 15, false, 'Plan 1', 'Fibra', 70, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Latin American Cable'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 400, 25, false, 'Plan 2', 'Fibra', 70, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Latin American Cable'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 35, false, 'Plan 3', 'Fibra', 70, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Latin American Cable'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 700, 41, false, 'Plan 4', 'Fibra', 70, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Full Data'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 29, false, 'Plan 1', 'FTTH', 35, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Full Data'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 25, false, 'Plan 2', 'FTTH', 35, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Full Data'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 800, 35, false, 'Plan 3', 'FTTH', 35, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Full Data'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 90, false, 'Plan 4', 'FTTH', 35, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 100, 35, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV","precio":"0","condicion":"Incluido"},{"nombre":"ONT","precio":"25","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 200, 42, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 600, 60, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Distrito Capital', 'Libertador', 'Sucre', 'Actualización General', 1000, 80, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado');

-- ============ EL VALLE ============
INSERT INTO ofertas_competencia (operador_id, estado, municipio, parroquia, tipo_novedad, velocidad_mb, precio_mensual, es_promocion, nombre_plan, tecnologia, costo_instalacion, servicios_adicionales, fuente, fecha_reporte, asesor_nombre) VALUES
((SELECT id FROM operadores_competencia WHERE nombre='Cable Norte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 400, 25.50, false, 'Plan 1', 'FTTH', 10, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Cable Norte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 600, 37.80, false, 'Plan 2', 'FTTH', 10, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Cable Norte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 800, 50.40, false, 'Plan 3', 'FTTH', 10, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Thundernet'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 400, 29, false, 'ThunderLIFE', 'XGS-PON', 30, '[{"nombre":"TV GO","precio":"0","condicion":"Incluido"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Thundernet'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 750, 58, false, 'ThunderVOLT', 'XGS-PON', 30, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Thundernet'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 1000, 82, false, 'ThunderPRO', 'XGS-PON', 30, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='Thundernet'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 2500, 352, false, 'ThunderSTORM', 'XGS-PON', 30, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SmartByte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 150, 29, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV","precio":"0","condicion":"Incluido"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SmartByte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 450, 40.60, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SmartByte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 650, 52.20, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='SmartByte'), 'Distrito Capital', 'Libertador', 'El Valle', 'Actualización General', 850, 63.80, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado');

-- ============ TEJERÍAS ============
INSERT INTO ofertas_competencia (operador_id, estado, municipio, parroquia, tipo_novedad, velocidad_mb, precio_mensual, es_promocion, nombre_plan, tecnologia, costo_instalacion, servicios_adicionales, fuente, fecha_reporte, asesor_nombre) VALUES
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Aragua', 'Santos Michelena', 'Las Tejerías', 'Actualización General', 100, 35, false, 'Plan 1', 'FTTH', 0, '[{"nombre":"TV","precio":"0","condicion":"Incluido"},{"nombre":"ONT","precio":"25","condicion":"Compra"}]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Aragua', 'Santos Michelena', 'Las Tejerías', 'Actualización General', 200, 42, false, 'Plan 2', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Aragua', 'Santos Michelena', 'Las Tejerías', 'Actualización General', 600, 60, false, 'Plan 3', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado'),
((SELECT id FROM operadores_competencia WHERE nombre='ABA Ultra'), 'Aragua', 'Santos Michelena', 'Las Tejerías', 'Actualización General', 1000, 80, false, 'Plan 4', 'FTTH', 0, '[]'::jsonb, 'excel_estudio', CURRENT_DATE, 'Estudio de Mercado');
